version: '3.9'

services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "chats-bot"

    volumes:
      - ../app/:/app/
      - ../.env:/app/.env

    command: "debugpy --listen 0.0.0.0:5678 main.py"

    ports:
      - "5679:5678"
